version: '3.3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'api_base'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'juan'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - './migrations/schema.sql:/docker-entrypoint-initdb.d/init.sql'